### ISSUE TITLE
Not a V3 wallet

### ISSUE THREAD

**Issue by lsaether** [ethereum-alarm-clock/eac.js-cli#6]
when trying to run the cli timenode with mutliple v3 wallets in one keystore (ex. cli/keyz) the program throws the error `not a v3 wallet`. 

Find the source of this issue and fix it.

It's probably due to the way that it is parsing the keystore file, it should treat each item in the keystore file as its own V3 wallet.

**Comment by adibas03** [comment]
Fixed by https://github.com/ethereum-alarm-clock/eac.js-cli/pull/8
